version: '3.7'
networks:
  app-network:
      driver: bridge
services:
  db:
    image: mysql:5.7
    ports:
        - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      -  app-network
    deploy:
      resources:
        limits:
          memory: 300m
        reservations:
          memory: 100m
  wordpress:
    depends_on:
      - db
    image: wordpress:5.8.3-fpm-alpine
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: DB:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 300m
        reservations:
          memory: 100m
  server:
    image: nginx:1.15.12-alpine
    depends_on:
      - wordpress
    restart: always
    ports:
      - '80:80'
    volumes:
      - wordpress_data:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d/
    networks:
      -  app-network
volumes:
  db_data: {}
  wordpress_data: {}

